const fs = require('node:fs');
const http = require('node:http');
const path = require('node:path');

const {
  assertNonEmptyCode,
  createDemoPackageRoot,
  ensurePluginScaffoldExists,
  ensureTargetDirForInit,
  getPluginName,
  log,
  removeDirIfExists,
  sanitizeCode,
  writeFile,
  writeKeepFile,
} = require('./fs.js');
const {
  createCargoTomlTemplate,
  createExampleModelYaml,
  createI18nTemplate,
  createManifestTemplate,
  createProviderYamlTemplate,
  createReadmeTemplate,
  createRustMainTemplate,
  readPluginCode,
} = require('./manifest.js');

const DEFAULT_DEMO_HOST = '127.0.0.1';
const DEFAULT_DEMO_PORT = 4310;
const DEFAULT_RUNNER_URL = 'http://127.0.0.1:7801';

function createDemoIndexHtml({ pluginName }) {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>1flowbase Plugin Demo</title>
    <link rel="stylesheet" href="./styles.css" />
  </head>
  <body>
    <main class="layout">
      <header class="hero">
        <p class="eyebrow">1flowbase Plugin Demo</p>
        <h1>${pluginName}</h1>
        <p class="subtitle">Local provider demo scaffold generated by the host-side plugin CLI.</p>
        <div class="meta">
          <span id="runner-status" class="status-chip">Runner: checking</span>
          <span id="runner-url" class="status-chip">URL: loading</span>
        </div>
      </header>

      <section class="card" id="provider-instance">
        <h2>Provider Instance</h2>
        <label>Base URL <input id="base-url" value="https://api.example.com" /></label>
        <label>API Key <input id="api-key" type="password" value="sk-demo-key" /></label>
        <label>Default Model <input id="default-model" value="example-chat" /></label>
      </section>

      <section class="card">
        <div class="card-header">
          <h2>Validate</h2>
          <button id="validate-button" type="button">Run Validate</button>
        </div>
        <pre id="validate-output">Waiting for validation.</pre>
      </section>

      <section class="card">
        <div class="card-header">
          <h2>List Models</h2>
          <button id="list-models-button" type="button">List Models</button>
        </div>
        <pre id="models-output">No models fetched yet.</pre>
      </section>

      <section class="card">
        <div class="card-header">
          <h2>Prompt / Stream</h2>
          <button id="stream-button" type="button">Run Stream</button>
        </div>
        <textarea id="prompt-input" rows="4">Write a concise summary of this provider integration.</textarea>
        <pre id="stream-output">No stream yet.</pre>
      </section>

      <section class="card">
        <div class="card-header">
          <h2>Tool Call / MCP</h2>
          <button id="tool-button" type="button">Simulate Tool Call</button>
        </div>
        <pre id="tool-output">No tool call yet.</pre>
      </section>

      <section class="card">
        <h2>Usage / Token</h2>
        <dl class="usage-grid">
          <div>
            <dt>Prompt Tokens</dt>
            <dd id="prompt-tokens">0</dd>
          </div>
          <div>
            <dt>Completion Tokens</dt>
            <dd id="completion-tokens">0</dd>
          </div>
          <div>
            <dt>Total Tokens</dt>
            <dd id="total-tokens">0</dd>
          </div>
        </dl>
      </section>
    </main>

    <script src="./app.js"></script>
  </body>
</html>
`;
}

function createDemoStylesCss() {
  return `:root {
  color-scheme: light;
  --bg: #f4efe6;
  --panel: rgba(255, 250, 242, 0.92);
  --panel-strong: #fff7ec;
  --text: #1e1a17;
  --muted: #6f6258;
  --accent: #a24d2c;
  --accent-ink: #fff8f0;
  --border: rgba(162, 77, 44, 0.18);
  --shadow: 0 18px 48px rgba(104, 63, 41, 0.12);
  font-family: "IBM Plex Sans", "Segoe UI", sans-serif;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  min-height: 100vh;
  background:
    radial-gradient(circle at top left, rgba(255, 213, 170, 0.5), transparent 32%),
    linear-gradient(180deg, #f7f1e8 0%, #efe4d6 100%);
  color: var(--text);
}

.layout {
  width: min(1120px, calc(100% - 32px));
  margin: 0 auto;
  padding: 32px 0 56px;
  display: grid;
  gap: 18px;
}

.hero,
.card {
  background: var(--panel);
  border: 1px solid var(--border);
  border-radius: 22px;
  box-shadow: var(--shadow);
}

.hero {
  padding: 28px;
}

.eyebrow {
  margin: 0 0 10px;
  color: var(--accent);
  font-size: 13px;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.hero h1,
.card h2 {
  margin: 0;
  font-family: "IBM Plex Serif", "Georgia", serif;
}

.subtitle {
  margin: 10px 0 0;
  color: var(--muted);
  line-height: 1.5;
}

.meta {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  margin-top: 18px;
}

.status-chip {
  display: inline-flex;
  align-items: center;
  padding: 6px 10px;
  border-radius: 999px;
  background: var(--panel-strong);
  border: 1px solid var(--border);
  color: var(--muted);
  font-size: 13px;
}

.card {
  padding: 22px;
  display: grid;
  gap: 14px;
}

.card-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
}

label {
  display: grid;
  gap: 8px;
  font-weight: 600;
}

input,
textarea,
button {
  font: inherit;
}

input,
textarea {
  width: 100%;
  padding: 12px 14px;
  border-radius: 14px;
  border: 1px solid rgba(111, 98, 88, 0.22);
  background: #fffdf9;
}

button {
  border: 0;
  border-radius: 14px;
  padding: 11px 16px;
  background: var(--accent);
  color: var(--accent-ink);
  cursor: pointer;
  font-weight: 700;
}

button:hover {
  filter: brightness(1.06);
}

pre {
  margin: 0;
  padding: 16px;
  border-radius: 16px;
  background: #1f1b18;
  color: #f6efe7;
  overflow: auto;
  white-space: pre-wrap;
}

.usage-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
  gap: 12px;
  margin: 0;
}

.usage-grid div {
  padding: 14px;
  border-radius: 16px;
  background: var(--panel-strong);
  border: 1px solid var(--border);
}

.usage-grid dt {
  margin: 0 0 6px;
  color: var(--muted);
  font-size: 13px;
}

.usage-grid dd {
  margin: 0;
  font-size: 28px;
  font-weight: 700;
}

@media (max-width: 720px) {
  .layout {
    width: min(100%, calc(100% - 20px));
    padding-top: 18px;
  }

  .hero,
  .card {
    border-radius: 18px;
    padding: 18px;
  }

  .card-header {
    flex-direction: column;
    align-items: stretch;
  }
}
`;
}

function createDemoAppJs() {
  return `(async function bootstrapDemo() {
  const state = {
    promptTokens: 0,
    completionTokens: 0,
  };

  async function loadConfig() {
    const response = await fetch('/__plugin_demo_config');
    return response.json();
  }

  function setOutput(id, value) {
    document.getElementById(id).textContent =
      typeof value === 'string' ? value : JSON.stringify(value, null, 2);
  }

  function updateUsage(promptTokens, completionTokens) {
    state.promptTokens = promptTokens;
    state.completionTokens = completionTokens;
    document.getElementById('prompt-tokens').textContent = String(promptTokens);
    document.getElementById('completion-tokens').textContent = String(completionTokens);
    document.getElementById('total-tokens').textContent = String(promptTokens + completionTokens);
  }

  const config = await loadConfig();
  document.getElementById('runner-url').textContent = 'URL: ' + config.runnerUrl;

  try {
    const healthResponse = await fetch(config.runnerUrl.replace(/\\/$/, '') + '/health');
    document.getElementById('runner-status').textContent =
      healthResponse.ok ? 'Runner: reachable' : 'Runner: unavailable';
  } catch (error) {
    document.getElementById('runner-status').textContent = 'Runner: unreachable';
  }

  document.getElementById('validate-button').addEventListener('click', () => {
    const baseUrl = document.getElementById('base-url').value;
    const apiKey = document.getElementById('api-key').value;
    setOutput('validate-output', {
      ok: true,
      providerCode: config.providerCode,
      base_url: baseUrl,
      api_key_present: Boolean(apiKey),
      note: 'This is a scaffold response. Wire it to the real debug runtime later.',
    });
  });

  document.getElementById('list-models-button').addEventListener('click', () => {
    setOutput('models-output', [
      { code: config.providerCode + '_chat', label: 'Example Chat Model', mode: 'chat' },
      { code: config.providerCode + '_reasoning', label: 'Example Reasoning Model', mode: 'reasoning' },
      { code: config.providerCode + '_vision', label: 'Example Vision Model', mode: 'multimodal' },
    ]);
  });

  document.getElementById('stream-button').addEventListener('click', async () => {
    const prompt = document.getElementById('prompt-input').value.trim();
    const tokens = prompt ? Math.max(8, Math.ceil(prompt.length / 4)) : 8;
    const chunks = [
      'Streaming scaffold connected. ',
      'Replace this animation with real provider events. ',
      'Prompt preview: ' + prompt.slice(0, 48),
    ];

    setOutput('stream-output', '');
    let rendered = '';
    for (const chunk of chunks) {
      rendered += chunk;
      setOutput('stream-output', rendered);
      await new Promise((resolve) => setTimeout(resolve, 90));
    }

    updateUsage(tokens, 24);
  });

  document.getElementById('tool-button').addEventListener('click', () => {
    setOutput('tool-output', {
      tool_call: {
        tool: 'search_docs',
        arguments: { query: 'provider kernel contract' },
      },
      mcp_call: {
        server: 'docs',
        method: 'search',
      },
      status: 'scaffold_only',
    });
  });

  updateUsage(0, 0);
})();`;
}

function createDemoRunnerConfigTemplate({ pluginCode }) {
  return JSON.stringify(
    {
      providerCode: pluginCode,
      runnerUrl: DEFAULT_RUNNER_URL,
      notes: [
        'This file is for local demo wiring hints only.',
        'Real plugin-runner debug runtime integration is not implemented in this scaffold yet.',
      ],
    },
    null,
    2
  ) + '\n';
}

function createPluginScaffold(pluginPath, options = {}) {
  const pluginName = getPluginName(pluginPath);
  const pluginCode = assertNonEmptyCode(
    sanitizeCode(options.providerCode || pluginName),
    'provider code'
  );

  ensureTargetDirForInit(pluginPath);

  writeFile(
    path.join(pluginPath, 'manifest.yaml'),
    createManifestTemplate({ pluginCode, pluginName })
  );
  writeFile(
    path.join(pluginPath, 'provider', `${pluginCode}.yaml`),
    createProviderYamlTemplate({ pluginCode, pluginName })
  );
  writeFile(path.join(pluginPath, 'Cargo.toml'), createCargoTomlTemplate({ pluginCode }));
  writeFile(
    path.join(pluginPath, 'src', 'main.rs'),
    createRustMainTemplate({ pluginCode })
  );
  writeFile(
    path.join(pluginPath, 'models', 'llm', '_position.yaml'),
    'items:\n  - example\n'
  );
  writeFile(
    path.join(pluginPath, 'models', 'llm', `${pluginCode}_chat.yaml`),
    createExampleModelYaml({ pluginCode })
  );
  writeFile(
    path.join(pluginPath, 'i18n', 'en_US.json'),
    createI18nTemplate({ pluginName, locale: 'en_US' })
  );
  writeFile(
    path.join(pluginPath, 'i18n', 'zh_Hans.json'),
    createI18nTemplate({ pluginName, locale: 'zh_Hans' })
  );
  writeFile(
    path.join(pluginPath, 'readme', 'README_en_US.md'),
    createReadmeTemplate({ pluginCode, pluginName })
  );
  writeKeepFile(path.join(pluginPath, 'demo', '.gitkeep'));
  writeKeepFile(path.join(pluginPath, 'scripts', '.gitkeep'));
  writeKeepFile(path.join(pluginPath, '_assets', '.gitkeep'));

  return {
    pluginPath,
    pluginName,
    pluginCode,
  };
}

function createPluginDemoScaffold(pluginPath) {
  ensurePluginScaffoldExists(pluginPath);

  const pluginName = getPluginName(pluginPath);
  const pluginCode = readPluginCode(pluginPath);

  writeFile(path.join(pluginPath, 'demo', 'index.html'), createDemoIndexHtml({ pluginName }));
  writeFile(path.join(pluginPath, 'demo', 'styles.css'), createDemoStylesCss());
  writeFile(path.join(pluginPath, 'demo', 'app.js'), createDemoAppJs());
  writeFile(
    path.join(pluginPath, 'scripts', 'demo.runner.example.json'),
    createDemoRunnerConfigTemplate({ pluginCode })
  );

  return {
    pluginPath,
    pluginName,
    pluginCode,
  };
}

function resolvePort(value) {
  if (value == null) {
    return DEFAULT_DEMO_PORT;
  }

  const port = Number(value);
  if (!Number.isInteger(port) || port < 0 || port > 65535) {
    throw new Error(`非法端口：${value}`);
  }

  return port;
}

function getContentType(filePath) {
  if (filePath.endsWith('.html')) {
    return 'text/html; charset=utf-8';
  }
  if (filePath.endsWith('.css')) {
    return 'text/css; charset=utf-8';
  }
  if (filePath.endsWith('.js')) {
    return 'application/javascript; charset=utf-8';
  }
  if (filePath.endsWith('.json')) {
    return 'application/json; charset=utf-8';
  }
  return 'text/plain; charset=utf-8';
}

function readStaticFile(demoDir, requestPath) {
  const normalized = requestPath === '/' ? '/index.html' : requestPath;
  const fullPath = path.normalize(path.join(demoDir, normalized));

  if (!fullPath.startsWith(path.normalize(demoDir + path.sep))) {
    return null;
  }

  if (!fs.existsSync(fullPath) || !fs.statSync(fullPath).isFile()) {
    return null;
  }

  return fullPath;
}

async function startDemoServer(options) {
  const pluginPath = path.resolve(options.pluginPath);
  const demoDir = path.join(pluginPath, 'demo');
  const indexPath = path.join(demoDir, 'index.html');
  if (!fs.existsSync(indexPath)) {
    throw new Error(`缺少 demo 资源，请先执行 plugin demo init：${pluginPath}`);
  }

  const pluginCode = readPluginCode(pluginPath);
  const host = options.host || DEFAULT_DEMO_HOST;
  const port = resolvePort(options.port);
  const runnerUrl = options.runnerUrl || DEFAULT_RUNNER_URL;
  const silent = Boolean(options.silent);
  const packageRoot = createDemoPackageRoot(pluginPath);

  const server = http.createServer((request, response) => {
    const url = new URL(request.url || '/', `http://${request.headers.host || 'localhost'}`);
    if (url.pathname === '/__plugin_demo_config') {
      response.writeHead(200, { 'content-type': 'application/json; charset=utf-8' });
      response.end(
        JSON.stringify(
          {
            providerCode: pluginCode,
            pluginPath,
            packageRoot,
            runnerUrl,
          },
          null,
          2
        )
      );
      return;
    }

    const staticPath = readStaticFile(demoDir, url.pathname);
    if (!staticPath) {
      response.writeHead(404, { 'content-type': 'text/plain; charset=utf-8' });
      response.end('Not Found');
      return;
    }

    response.writeHead(200, { 'content-type': getContentType(staticPath) });
    response.end(fs.readFileSync(staticPath));
  });

  try {
    await new Promise((resolve, reject) => {
      server.once('error', reject);
      server.listen(port, host, resolve);
    });
  } catch (error) {
    removeDirIfExists(packageRoot);
    throw error;
  }

  const address = server.address();
  const resolvedPort = typeof address === 'object' && address ? address.port : port;
  const baseUrl = `http://${host}:${resolvedPort}`;
  log(`Demo server ready at ${baseUrl}`, { silent });
  log(`Runner URL set to ${runnerUrl}`, { silent });
  let closed = false;

  return {
    server,
    baseUrl,
    close: () =>
      new Promise((resolve, reject) => {
        if (closed) {
          resolve();
          return;
        }
        closed = true;
        server.close((error) => {
          removeDirIfExists(packageRoot);
          if (error) {
            reject(error);
            return;
          }
          resolve();
        });
      }),
  };
}

module.exports = {
  DEFAULT_DEMO_HOST,
  DEFAULT_DEMO_PORT,
  DEFAULT_RUNNER_URL,
  createPluginDemoScaffold,
  createPluginScaffold,
  resolvePort,
  startDemoServer,
};
